# Generated by Django 3.2.3 on 2021-05-15 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='vehicle',
            new_name='vehicle_name',
        ),
    ]
